- name: Add ArgoCD chart repo
  kubernetes.core.helm_repository:
    name: argo
    repo_url: https://argoproj.github.io/argo-helm

- name: Deploy ArgoCD
  kubernetes.core.helm:
    name: argocd
    chart_ref: argo/argo-cd
    chart_version: 8.2.5
    release_namespace: argocd
    create_namespace: true
    kubeconfig: ${HOME}/.k0s/admin.conf
    validate_certs: false
    values:
      configs:
        params:
          server.insecure: true

