- name: Clone portfolio ArgoCD Helm repository
  ansible.builtin.git:
    repo: https://github.com/aidenharwood/portfolio-helm-argocd-bootstrap.git
    dest: /tmp/portfolio-helm-argocd

# - name: Install ArgoCD Helm chart
#   kubernetes.core.helm:
#     name: argocd
#     chart_ref: /tmp/portfolio-helm-argocd
#     release_namespace: argocd
#     create_namespace: true
#     values: {}
#     context: ~/k0s.admin.conf

- name: Install ArgoCD Helm chart
  ansible.builtin.shell:
    cmd: |
      helm dependency build .
      helm upgrade --install argocd . --namespace argocd --create-namespace
    chdir: /tmp/portfolio-helm-argocd
  environment:
    KUBECONFIG: /var/lib/k0s/pki/admin.conf