- name: Install kubectl
  ansible.builtin.apt:
    name: kubectl
    state: present

- name: Install helm
  community.general.snap:
    name: helm
    classic: true
    state: present

- name: Install k0s
  ansible.builtin.get_url:
    url: https://get.k0s.sh
    dest: /tmp/get-k0s.sh
    mode: "0755"

- name: Run k0s installer
  ansible.builtin.shell: /tmp/get-k0s.sh
  args:
    creates: /usr/local/bin/k0s

- name: Ensure k0s is running
  ansible.builtin.systemd:
    name: k0scontroller
    state: started
    enabled: true

- name: Make k0s kubeconfig available
  ansible.builtin.file:
    path: /var/lib/k0s/pki/admin.conf
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
