- name: Install kubectl
  ansible.builtin.apt:
    name: kubectl
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install helm
  community.general.snap:
    name: helm
    classic: true
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install k0s
  ansible.builtin.get_url:
    url: https://get.k0s.sh
    dest: /tmp/get-k0s.sh
    mode: "0755"
  when: ansible_distribution == "Ubuntu"

- name: Run k0s installer
  ansible.builtin.shell: /tmp/get-k0s.sh
  args:
    creates: /usr/local/bin/k0s
  when: ansible_distribution == "Ubuntu"

- name: Ensure k0s is running
  ansible.builtin.systemd:
    name: k0scontroller
    state: started
    enabled: true
  when: ansible_distribution == "Ubuntu"

- name: Configure kubectl for k0s
  ansible.builtin.command:
    cmd: k0s kubectl config view --raw > ~/k0s.admin.conf
  when: ansible_distribution == "Ubuntu"

- name: Set KUBECONFIG environment variable
  ansible.builtin.set_fact:
    kubectl_config: ~/k0s.admin.conf
  when: ansible_distribution == "Ubuntu"
  