- name: Install kubectl
  community.general.snap:
    name: kubectl
    classic: true
    state: present
    
- name: Install helm
  community.general.snap:
    name: helm
    classic: true
    state: present

- name: Install multipass
  community.general.snap:
    name: multipass
    classic: true
    state: present

- name: Install k9s
  community.general.snap:
    name: k9s
    classic: true
    state: present
    
- name: Create k9s symlink
  ansible.builtin.shell: |
    ln -s /snap/k9s/current/bin/k9s /usr/bin/k9s

- name: Setup K0s Cluster
  ansible.builtin.shell: |    
    mkdir ~/.ssh
    ssh-keygen 
    ssh-keygen -t ed25519 -q -f ~/.ssh/id_ed25519 -N ""
    
    git clone https://github.com/movd/k0s-ansible.git k0s-ansible
    k0s-ansible/tools/multipass_create_instances.sh
    k0s-ansible/tools/multipass_generate_inventory.py

    for host in $(awk '/ansible_host/ {print $2}' ansible/tools/inventory.yml); do
      ssh-keyscan $host >> ~/.ssh/known_hosts
    done
    
    ansible -i k0s-ansible/tools/inventory.yml all -m ping
    
    ansible-playbook k0s-ansible/site.yml -i k0s-ansible/tools/inventory.yml

    mkdir ~/.kube
    cp k0s-ansible/tools/artifacts/k0s-kubeconfig.yml ~/.kube/config

    rm -rf k0s-ansible

- name: Open firewall for k0s
  ansible.builtin.shell: |
    ufw allow 22/tcp    #  
    ufw allow 6443/tcp  # These should be locked to lan-only (no use putting masks in GH)
    ufw allow 10250/tcp #
    ufw allow 80/tcp
    ufw allow 443/tcp
    ufw enable
