- name: Install prerequisite software
  become: yes
  tasks:
    - name: Install kubectl
      ansible.builtin.get_url:
        url: https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: "0755"
      when: ansible_os_family != "Windows"

    - name: Install helm
      ansible.builtin.shell: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        creates: /usr/local/bin/helm
      when: ansible_os_family != "Windows"

    - name: Install k0s
      ansible.builtin.get_url:
        url: https://get.k0s.sh
        dest: /tmp/get-k0s.sh
        mode: "0755"
      when: ansible_os_family != "Windows"

    - name: Run k0s installer
      ansible.builtin.shell: /tmp/get-k0s.sh
      args:
        creates: /usr/local/bin/k0s
      when: ansible_os_family != "Windows"
