- name: Install kubectl
  ansible.builtin.shell: |
      curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

- name: Install helm
  community.general.snap:
    name: helm
    classic: true
    state: present

- name: Install yq
  ansible.builtin.apt:
    name: yq
    state: present

- name: Download k0s installer
  ansible.builtin.get_url:
    url: https://get.k0s.sh
    dest: /tmp/get-k0s.sh
    mode: "0755"

- name: Run k0s installer
  ansible.builtin.shell: /tmp/get-k0s.sh
  args:
    creates: /usr/local/bin/k0s

- name: Create k0s configuration directory
  ansible.builtin.file:
    path: ${HOME}/.k0s
    state: directory

- name: Create k0s config
  ansible.builtin.shell: k0s config create > ${HOME}/.k0s/k0s.yaml

- name: Install k0s controller/worker
  ansible.builtin.shell: k0s install controller --config ${HOME}/.k0s/k0s.yaml --enable-worker

- name: Start k0s
  ansible.builtin.shell: service k0scontroller start

- name: Initialize k0s credentials
  ansible.builtin.shell: |
    k0s kubeconfig admin | yq >> ${HOME}/.kube/config

- name: Ensure k0s is running
  ansible.builtin.systemd:
    name: k0scontroller
    state: started
    enabled: true

- name: Open firewall for k0s
  ansible.builtin.shell: |
    sudo ufw allow 6443/tcp
    sudo ufw allow 80/tcp
    sudo ufw allow 443/tcp
    sudo ufw allow 10250/tcp
    sudo ufw reload
