- name: Install kubectl
  ansible.builtin.shell:
    cmd: |
      curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    state: present

- name: Install helm
  community.general.snap:
    name: helm
    classic: true
    state: present

- name: Install k0s
  ansible.builtin.get_url:
    url: https://get.k0s.sh
    dest: /tmp/get-k0s.sh
    mode: "0755"

- name: Run k0s installer
  ansible.builtin.shell: /tmp/get-k0s.sh
  args:
    creates: /usr/local/bin/k0s

- name: Ensure k0s is running
  ansible.builtin.systemd:
    name: k0scontroller
    state: started
    enabled: true

- name: Make k0s kubeconfig available
  ansible.builtin.file:
    path: /var/lib/k0s/pki/admin.conf
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0644"
