- name: Configure k8s host
  hosts: all
  become: true
  tasks:
    - include_tasks: tasks/prerequisites.yaml
    - include_tasks: tasks/helm-argocd.yaml
    - include_tasks: tasks/helm-argocd-bootstrap.yaml